# Generated by Django 3.2.8 on 2022-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, max_length=256)),
                ('col2', models.CharField(blank=True, max_length=256)),
                ('col3', models.CharField(blank=True, max_length=256)),
                ('col4', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
