# Generated by Django 3.2.8 on 2022-12-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIGGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.FloatField(blank=True)),
                ('col2', models.FloatField(blank=True)),
                ('col3', models.FloatField(blank=True)),
                ('col4', models.FloatField(blank=True)),
                ('col5', models.FloatField(blank=True)),
                ('col6', models.FloatField(blank=True)),
                ('col7', models.FloatField(blank=True)),
                ('col8', models.FloatField(blank=True)),
                ('col9', models.FloatField(blank=True)),
                ('col10', models.FloatField(blank=True)),
                ('col11', models.FloatField(blank=True)),
                ('col12', models.FloatField(blank=True)),
                ('col13', models.FloatField(blank=True)),
                ('col14', models.FloatField(blank=True)),
                ('col15', models.FloatField(blank=True)),
                ('col16', models.FloatField(blank=True)),
                ('col17', models.FloatField(blank=True)),
                ('col18', models.FloatField(blank=True)),
                ('col19', models.FloatField(blank=True)),
                ('col20', models.FloatField(blank=True)),
                ('col21', models.FloatField(blank=True)),
                ('col22', models.FloatField(blank=True)),
                ('col23', models.FloatField(blank=True)),
                ('col24', models.FloatField(blank=True)),
                ('col25', models.FloatField(blank=True)),
                ('col26', models.FloatField(blank=True)),
                ('col27', models.FloatField(blank=True)),
                ('col28', models.FloatField(blank=True)),
                ('col29', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True)),
                ('dataurl', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
